'use client';
import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import {Check,Clock,ImagePlus,Pencil,Play,Plus,RotateCcw,Settings,Sparkles,Trash2,Users,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from '@/components/ui/dialog';
type Person={id:string;name:string;photo:string}; type Choice={value:string;correct:boolean};
const KEY='name-match-people-v1';
const similar:Record<string,string[]>={王:['玉','主'],玉:['王','主'],明:['朋','眀'],婷:['庭','亭'],晴:['睛','精'],睛:['晴','精'],宇:['字','守'],安:['按','案'],怡:['宜','依'],佳:['加','嘉'],嘉:['佳','加'],瑄:['宣','萱'],萱:['宣','瑄'],翔:['祥','詳'],祥:['翔','詳'],宏:['弘','洪'],弘:['宏','洪'],祐:['佑','右'],佑:['祐','右'],妤:['瑜','愉'],豪:['濠','毫'],毅:['義','議'],芯:['心','欣'],欣:['芯','心'],潔:['捷','婕']};
const extras='王玉主日目木禾大太天子字宇心芯欣佳加嘉晴睛精庭婷亭祥翔詳佑祐右';
const confusionGroups=['王玉主','日目曰','木本末未','土士','大太犬','人入八','子孑字','宇守字','明朋眀','晴睛精清情','佳加嘉','婷庭亭','瑄宣萱','翔祥詳','宏弘洪','祐佑右','妤瑜愉','芯心欣','潔捷婕','豪毫濠','毅義議','林琳霖','玲鈴伶','偉緯瑋','維唯惟','庭廷霆','承丞成','哲喆','涵函','恩思','宥有','柏百伯','睿叡','凱愷','銘名','晨辰宸','萓宜怡','昕欣芯','彥諺顏','薇微','慧惠','芸雲','筠均','甯寧','綺琦琪','駿俊','勳熏','瑋偉緯'];
function shuffle<T>(a:T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r}
function choices(answer:string,people:Person[]):Choice[]{const group=confusionGroups.find(chars=>chars.includes(answer));const similarPool=[...(similar[answer]??[]),...Array.from(group??'')].filter((c,i,a)=>c!==answer&&a.indexOf(c)===i);const similarChar=shuffle(similarPool)[0]??shuffle(Array.from(extras).filter(c=>c!==answer))[0];const libraryPool=people.flatMap(p=>Array.from(p.name)).filter((c,i,a)=>c!==answer&&c!==similarChar&&a.indexOf(c)===i);const libraryChar=shuffle(libraryPool)[0]??shuffle(Array.from(extras).filter(c=>c!==answer&&c!==similarChar))[0];return shuffle([{value:answer,correct:true},{value:similarChar,correct:false},{value:libraryChar,correct:false}])}
function arrangeWithoutRepeat(items:Person[]){const counts=new Map<string,{person:Person;count:number}>();items.forEach(person=>{const entry=counts.get(person.id);counts.set(person.id,{person,count:(entry?.count??0)+1})});const result:Person[]=[];while(counts.size){const candidates=shuffle([...counts.values()]).sort((a,b)=>b.count-a.count).filter(entry=>entry.person.id!==result.at(-1)?.id);const chosen=candidates[0];if(!chosen)break;result.push(chosen.person);chosen.count--;if(chosen.count===0)counts.delete(chosen.person.id)}return result}
function makeRound(people:Person[]){const n=people.length;if(n<5)return arrangeWithoutRepeat([...people,...people]);if(n<=15){const items=[...people];while(items.length<15){const counts=people.map(person=>({person,count:items.filter(item=>item.id===person.id).length})),minimum=Math.min(...counts.map(item=>item.count)),candidates=counts.filter(item=>item.count===minimum).map(item=>item.person);items.push(shuffle(candidates)[0])}return arrangeWithoutRepeat(items)}return shuffle(people).slice(0,15)}
function formatTime(ms:number){const total=Math.floor(ms/1000),minutes=Math.floor(total/60),seconds=total%60,tenths=Math.floor(ms%1000/100);return `${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}.${tenths}`}
async function resize(file:File){const source=await createImageBitmap(file),scale=Math.min(1,900/Math.max(source.width,source.height)),canvas=document.createElement('canvas');canvas.width=Math.round(source.width*scale);canvas.height=Math.round(source.height*scale);canvas.getContext('2d')?.drawImage(source,0,0,canvas.width,canvas.height);source.close();return canvas.toDataURL('image/jpeg',.82)}
function playCorrectSound(){const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext,ctx=new AudioContextClass();[523,784].forEach((frequency,i)=>{const oscillator=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+i*.11;oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.14,start);gain.gain.exponentialRampToValueAtTime(.001,start+.24);oscillator.connect(gain).connect(ctx.destination);oscillator.start(start);oscillator.stop(start+.24)});setTimeout(()=>void ctx.close(),500)}
export default function Game({autoStartSignal=0,player=0}:{autoStartSignal?:number;player?:number}){
 const [people,setPeople]=useState<Person[]>([]),[loaded,setLoaded]=useState(false),[open,setOpen]=useState(false),[name,setName]=useState(''),[photo,setPhoto]=useState(''),[editId,setEditId]=useState<string|null>(null),[current,setCurrent]=useState<Person|null>(null),[index,setIndex]=useState(0),[opts,setOpts]=useState<Choice[]>([]),[picked,setPicked]=useState<string|null>(null),[score,setScore]=useState(0),[queue,setQueue]=useState<Person[]>([]),[questionNo,setQuestionNo]=useState(0),[startedAt,setStartedAt]=useState<number|null>(null),[elapsed,setElapsed]=useState(0),[status,setStatus]=useState<'idle'|'playing'|'finished'|'sessionDone'>('idle'),[message,setMessage]=useState('');
 useEffect(()=>{try{setPeople(JSON.parse(sessionStorage.getItem(KEY)??'[]'))}catch{setPeople([])}setLoaded(true)},[]);useEffect(()=>{if(loaded){sessionStorage.setItem(KEY,JSON.stringify(people));if(player===0)window.dispatchEvent(new CustomEvent('shared-name-roster',{detail:people}))}},[people,loaded,player]);useEffect(()=>{if(player!==1)return;const sync=(event:Event)=>setPeople((event as CustomEvent<Person[]>).detail);window.addEventListener('shared-name-roster',sync);return()=>window.removeEventListener('shared-name-roster',sync)},[player]);useEffect(()=>{if(startedAt===null||status==='sessionDone'||status==='idle')return;const timer=window.setInterval(()=>setElapsed(Date.now()-startedAt),100);return()=>window.clearInterval(timer)},[startedAt,status]);
 const reset=()=>{setName('');setPhoto('');setEditId(null)},upload=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f?.type.startsWith('image/'))setPhoto(await resize(f));e.target.value=''},save=()=>{if(!name.trim()||!photo)return;const p={id:editId??crypto.randomUUID(),name:name.trim(),photo};setPeople(a=>editId?a.map(x=>x.id===editId?p:x):[...a,p]);reset()},edit=(p:Person)=>{setEditId(p.id);setName(p.name);setPhoto(p.photo)},remove=(id:string)=>{setPeople(a=>a.filter(p=>p.id!==id));if(editId===id)reset()};
 const batchUpload=async(e:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files??[]).filter(file=>file.type.startsWith('image/'));const added=(await Promise.all(files.map(async file=>({id:crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,'').trim(),photo:await resize(file)})))).filter(person=>person.name);setPeople(all=>[...all,...added]);e.target.value=''};
 const loadQuestion=(p:Person)=>{setCurrent(p);setIndex(0);setOpts(choices(Array.from(p.name)[0],people));setPicked(null);setMessage('');setStatus('playing')};
 const start=(sharedSignal:unknown=0)=>{if(people.length<3){setOpen(true);return}const shared=typeof sharedSignal==='number'&&sharedSignal>0;let nextQueue:Person[];if(shared&&player===1){const ids=JSON.parse(sessionStorage.getItem('name-pk-queue')||'[]') as string[];nextQueue=ids.map(id=>people.find(p=>p.id===id)).filter(Boolean) as Person[];if(!nextQueue.length)nextQueue=makeRound(people)}else{nextQueue=makeRound(people);if(shared)sessionStorage.setItem('name-pk-queue',JSON.stringify(nextQueue.map(p=>p.id)))}const now=Date.now();setQueue(nextQueue);setQuestionNo(1);setScore(0);setStartedAt(now);setElapsed(0);loadQuestion(nextQueue[0])};
 useEffect(()=>{if(autoStartSignal>0)start(autoStartSignal)},[autoStartSignal]);
 const nextQuestion=()=>{const nextIndex=questionNo;if(nextIndex>=queue.length){setElapsed(startedAt?Date.now()-startedAt:elapsed);setStatus('sessionDone');return}setQuestionNo(nextIndex+1);loadQuestion(queue[nextIndex])};
 const choose=(o:Choice)=>{if(picked||!current)return;setPicked(o.value);if(!o.correct){setMessage('');setTimeout(()=>setPicked(null),3000);return}playCorrectSound();setScore(n=>n+1);setMessage('答對了！');setTimeout(()=>{const n=index+1;if(n>=Array.from(current.name).length){setIndex(n);if(questionNo>=queue.length){setElapsed(startedAt?Date.now()-startedAt:elapsed);setStatus('sessionDone');setMessage('全部完成！')}else{setStatus('finished');setMessage('你認出他了！')}}else{setIndex(n);setOpts(choices(Array.from(current.name)[n],people));setPicked(null);setMessage('')}},650)};
 const answered=current?Array.from(current.name).slice(0,index).join(''):'',total=useMemo(()=>current?Array.from(current.name).length:0,[current]),progress=current?Math.round(index/total*100):0,empty=loaded&&people.length===0;
 return <main className="game-shell"><header className="topbar"><div className="brand-mark"><Users/></div><div><p className="eyebrow">看照片・認名字</p><h1>認識你真好</h1></div><Dialog open={open} onOpenChange={v=>{setOpen(v);if(!v)reset()}}><DialogTrigger className="manage-button"><Settings/>管理題庫 <span>{people.length}</span></DialogTrigger><DialogContent className="manager-dialog"><DialogHeader><DialogTitle>管理真人照片與姓名</DialogTitle><DialogDescription>可一次上傳多張照片，檔名會自動成為姓名；例如「王小明.jpg」會建立為「王小明」。</DialogDescription></DialogHeader><label className="batch-upload"><ImagePlus/><span><strong>批次上傳照片</strong><small>支援 JPG、JPEG、PNG、WebP、GIF，可從電腦或雲端同步資料夾多選</small></span><input type="file" accept=".jpg,.jpeg,.png,.webp,.gif,image/jpeg,image/png,image/webp,image/gif" multiple onChange={batchUpload}/></label><div className="divider"><span>或逐筆新增、修改</span></div><div className="editor"><label className={`photo-input ${photo?'has-photo':''}`}>{photo?<img src={photo} alt="照片預覽"/>:<><ImagePlus/><span>選擇照片</span></>}<input type="file" accept=".jpg,.jpeg,.png,.webp,.gif,image/jpeg,image/png,image/webp,image/gif" onChange={upload}/></label><div className="name-editor"><label htmlFor="person-name">姓名</label><input id="person-name" value={name} maxLength={12} placeholder="例如：王小明" onChange={e=>setName(e.target.value)}/><p>遊戲會依照姓名順序，一次選一個字。</p></div><button className="save-button" disabled={!name.trim()||!photo} onClick={save}>{editId?<Check/>:<Plus/>}{editId?'儲存修改':'加入題庫'}</button>{editId&&<button className="cancel-button" onClick={reset}><X/>取消</button>}</div><div className="roster-head"><strong>目前名單</strong><span>{people.length} 人</span></div><div className="roster">{!people.length&&<div className="roster-empty">還沒有資料，請從上方加入第一位。</div>}{people.map(p=><div className="person-row" key={p.id}><img src={p.photo} alt={`${p.name}的照片`}/><strong>{p.name}</strong><button aria-label={`編輯${p.name}`} onClick={()=>edit(p)}><Pencil/></button><button className="delete" aria-label={`刪除${p.name}`} onClick={()=>remove(p.id)}><Trash2/></button></div>)}</div></DialogContent></Dialog></header>
 <section className="game-card"><div className="score-strip"><span>{status==='idle'?`題庫 ${people.length} 人`:`第 ${questionNo}／${queue.length} 題`}</span><span><Clock/>{formatTime(elapsed)}</span><span><Sparkles/>答對 {score} 個字</span></div>{status==='idle'&&<div className="welcome-state"><div className="photo-stage empty-photo"><Users/></div><h2>{empty?'先建立你的真人題庫':'準備好認識大家了嗎？'}</h2><p>{empty?'加入照片和姓名後，就能開始玩。':people.length<5?`共 ${people.length*2} 題，每位出現兩次。`:`本輪共 15 題，按下開始就會計時。`}</p><button className="primary-button" onClick={empty?()=>setOpen(true):start}>{empty?<Plus/>:<Play/>}{empty?'加入照片與姓名':'開始計時挑戰'}</button>{!empty&&people.length<3&&<p className="need-more">還要加入 {3-people.length} 人，才有足夠的三選一題目。</p>}</div>}
 {current&&status!=='idle'&&status!=='sessionDone'&&<div className="play-state"><div className="photo-stage"><img src={current.photo} alt="猜猜這是誰"/></div><div className="prompt-area"><p className="step-label">第 {Math.min(index+1,total)} 個字</p><div className="name-slots">{Array.from(current.name).map((c,i)=><span key={i} className={i<index||status==='finished'?'filled':i===index?'current':''}>{i<index||status==='finished'?c:'?'}</span>)}</div>{status==='playing'&&<><h2>{index===0?'他的名字，第一個字是？':`「${answered}」後面的字是？`}</h2><div className="choice-grid">{opts.map(o=>{const state=picked===o.value?(o.correct?'correct':'wrong'):'';return <button key={o.value} className={state} disabled={picked!==null} onClick={()=>choose(o)}>{o.value}{state==='correct'&&<Check/>}{state==='wrong'&&<X/>}</button>})}</div><div className={`feedback ${message?'show':''}`} role="status">{message}</div></>}{status==='finished'&&<div className="finish-panel"><Sparkles/><h2>{message}</h2><p>他的名字是 <strong>{current.name}</strong></p><button className="primary-button" onClick={nextQuestion}><Play/>下一題</button></div>}<div className="progress-track"><span style={{width:`${progress}%`}}/></div></div></div>}{status==='sessionDone'&&<div className="welcome-state"><div className="finish-panel"><Sparkles/><h2>挑戰完成！</h2><p>完成 {queue.length} 題的時間</p><strong className="final-time">{formatTime(elapsed)}</strong><p>共答對 {score} 個字</p><button className="primary-button" onClick={start}><RotateCcw/>再挑戰一次</button></div></div>}</section><p className="privacy-note">小提醒：請先取得本人或家長同意；關閉這個分頁後，照片與姓名題庫會自動清除。</p></main>
}
